---
- include: openshift-ansible-contrib/playbooks/cloudformation_setup.yml

- include: openshift-ansible-contrib/playbooks/group_setup.yml

- include: openshift-ansible-contrib/playbooks/ops_mirror.yml

- include: openshift-ansible/playbooks/byo/openshift-cluster/config.yml
  vars:
    ec2_region: us-east-1
    ec2_image: ami-7e14f213
    api_port: 443
    console_port: 443
    identity_providers:
    - name: htpasswd_auth
      login: true
      challenge: true
      kind: HTPasswdPasswordIdentityProvider
      filename: /etc/origin/master/htpasswd
    os_defaults:
    masters:
      count: "{{ num_masters | default(3) }}"
      instance_type: m4.xlarge
      vol_sizes:
        root: 15
        docker: 25
        etcd: 25
    infra_nodes:
      count: "{{ num_infra_nodes | default(2) }}"
      instance_type: m4.xlarge
      vol_sizes:
        root: 30
        docker: 25
    app_nodes:
      count: "{{ num_app_nodes | default(2) }}"
      instance_type: m4.xlarge
      vol_sizes:
        root: 30
        docker: 25
    hosted:
      vol_sizes:
        registry: 30
        logging: 30
        metrics: 30
    provider_defaults:
      ec2:
        tags:
          env: "{{ cluster_id }}"
        groups: ["tag_env_{{ cluster_id }}"]
        master:
          groups:
          - "tag_openshift-master_{{ cluster_id }}"
          - "tag_openshift-node_{{ cluster_id }}"
          - tag_node-region_master
          security_groups:
          - "{{ cluster_id }}-master"
          - "{{ cluster_id }}-node"
          tags:
            openshift-master: "{{ cluster_id }}"
            openshift-node: "{{ cluster_id }}"
            node-region: master
        node:
          groups:
          - "tag_openshift-node_{{ cluster_id }}"
          security_groups:
          - "{{ cluster_id }}-node"
          tags:
            openshift-node: "{{ cluster_id }}"
    deployment_type: "{{ deployment_type }}"
    openshift_cluster_id: "{{ cluster_id }}"
    openshift_debug_level: "{{ debug_level }}"
    openshift_node_debug_level: "{{ node_debug_level | default(debug_level, true) }}"
    openshift_node_kubelet_args:
      max-pods:
      - "100"
    openshift_cloudprovider_kind: aws
    openshift_master_debug_level: "{{ master_debug_level | default(debug_level, true) }}"
    openshift_master_access_token_max_seconds: 2419200
    openshift_master_identity_providers: "{{ identity_providers }}"
    openshift_master_api_port: "{{ console_port }}"
    openshift_master_console_port: "{{ console_port }}"
    openshift_package_version: 3.1.1.6
    openshift_master_logging_public_url: "https://kibana.{{ r53_wildcard_zone }}"
    openshift_master_metrics_public_url: "https://metrics.{{ r53_wildcard_zone }}/hawkular/metrics"
    osm_cluster_network_cidr: 10.0.0.0/8
    osm_host_subnet_length: 16
    osm_default_subdomain: "{{ r53_wildcard_zone }}"
    osm_default_node_selector: "env=demo"
    osm_use_cockpit: false
    openshift_master_cluster_method: native
    openshift_master_cluster_hostname: openshift.internal.{{ r53_host_zone }}
    openshift_master_cluster_public_hostname: openshift.{{ r53_host_zone }}
    os_firewall_enabled: False
